#Define the name of worklow
name: First Workflow
#When this worklow should be run
on: workflow_dispatch
jobs:
  #name of job
  first-job:
    #define the runner
    runs-on: ubuntu-latest
    #Steps to be executed
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print good bye
        run: |
          echo "Good bye"
          echo "See you again!"
    
  
  
